name: manage-azure-policy-f0425511
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy-Diagnostics-KeyVault_8a027594-85dd-4b76-bb38-71b240bc5823/**'
#      - .github/workflows/manage-azure-policy-f0425511.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f0425511}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy-Diagnostics-KeyVault_8a027594-85dd-4b76-bb38-71b240bc5823/**
